### ISSUE TITLE
Error: An error occurred while initializing user information

### ISSUE THREAD

**Issue by visionNoob** [khd2019/khd2019#16]
Error messages 
>.Error: An error occurred while initializing user information. Please contact dev team
>FATA[2019/11/29 15:34:55.875] Internal server error

**Comment by nsml-admin** [comment]
안녕하세요. 
서버문제가 있어서 작업하였습니다.
 다시한번 시도해보시겠어요? 

감사합니다.

**Comment by elzino** [comment]
저도 Error: An error occurred while initializing user information. Please contact dev team 라는 에러가 뜹니다.
행복코딩팀입니다

**Comment by visionNoob** [comment]
됩니다!

**Comment by nsml-admin** [comment]
@elzino 마찬가지 이유로 처리해 드렸습니다.

**Comment by parkchaesong** [comment]
> @elzino 마찬가지 이유로 처리해 드렸습니다.

저희도 An error occurred while initializing user information. level=fatal msg="Internal server error" 가 뜹니다. A조 13팀입니다!

**Comment by elzino** [comment]
.....
Building docker image. It might take for a while

까지만 나오고 더이상 진행이 안되는데 이유가 있을까요? 
도커는 #nsml: nvcr.io/nvidia/pytorch:19.09-py3 을 사용했습니다.

**Comment by brstar96** [comment]
저희 Paten팀도 아래와 같은 에러로 세션이 초기화되지 않습니다. 

Error: Fail to build docker image. Please Contact Dev team
time="2019/11/29 15:49:30.334" level=fatal msg="Internal server error"

**Comment by skfn20** [comment]
저희 조도 Error: An error occurred while initializing user information. Please contact dev team
time="2019/11/29 15:53:21.851" level=fatal msg="Internal server error"와 같은 문제가 나오고 있습니다.
A조 11팀입니다.

**Comment by nsml-admin** [comment]
@parkchaesong  @skfn20 처리해 드렸습니다.

@elzino 초기에 도커 이미지를 받는것 때문에 시간이 오래걸릴수 있는데 기다리시면 진행될걸로 보입니다.

@brstar96  세션네임과 함께 새로운 이슈로 만들어주시면 확인해보겠습니다.
