### ISSUE TITLE
(질문) 세션이 Allocated 에서 stuck 된 경우 

### ISSUE THREAD

**Issue by visionNoob** [khd2019/khd2019#18]
![image](https://user-images.githubusercontent.com/15168540/69849464-1f843400-12c0-11ea-87c1-9d77645163be.png)

다음과 같이 Allocated에서 세션이 멈춘 경우 어떻게 대처해야 하나요?

**Comment by siksimi** [comment]
저희도 같은 문제가 있습니다.
세션명 team116/None/12
세션명 team116/None/3

-d 로 dataset명 전달을 안하는경우에 문제가 생기는 것 같습니다.

**Comment by visionNoob** [comment]
nsml rm --force [teamname]/[datasetname]/[session_number]
로 해결했습니다.

**Comment by siksimi** [comment]
@visionNoob 감사합니다.
