### ISSUE TITLE
[질문] session Kill 문제 문의

### ISSUE THREAD

**Issue by mulkong** [khd2019/khd2019#19]
/bin/bash: line 1:    51 Killed                  python -u main.py
User session exited

라고 뜨게 됩니다.

**Comment by nsml-admin** [comment]
안녕하세요,

메모리 상의 문제로 추정됩니다.

https://github.com/khd2019/khd2019/issues/12#issue-530122859 를 참고하셔서 `nsml run` 할때 메모리 사이즈를 늘리거나 코드상에서 메모리를 적게사용하는방법으로 최적화를 하신후 다시 해보시기 바랍니다.

감사합니다.
