### ISSUE TITLE
타 지역 참가자의 경우 교통편 또는 교통비가 지원되나요?

### ISSUE THREAD

**Issue by kyoungsik-dev** [khd2019/khd2019#2]
안녕하세요,

타 지역 참가자의 경우 교통편 또는 교통비가 지원되는지 궁금합니다.

**Comment by khd2019** [comment]
안녕하세요.
KHD2019 운영사무국입니다.

본 행사는 2019.11.29(금) 12:00부터 등록을 시작하여 13:00부터는 오리엔테이션이 예정되어 있습니다. 
문의하신 별도의 교통편 및 교통비 지원은 없습니다. 

KHD2019는 2019.11.20(수)까지 
https://bit.ly/khd2019-nsml 로 참가신청이 가능하며 참가 여부는 심사 후 개별안내를 드립니다.

자세한 FAQ는 https://github.com/khd2019/khd2019 를 참고부탁드리겠습니다.
추가문의사항은 khd2019-nsml@navercorp.com로 문의주시면 회신드리겠습니다.

감사합니다.

> 안녕하세요,
> 
> 타 지역 참가자의 경우 교통편 또는 교통비가 지원되는지 궁금합니다.

**Comment by khd2019** [comment]
> 안녕하세요,
> 
> 타 지역 참가자의 경우 교통편 또는 교통비가 지원되는지 궁금합니다.

안녕하세요.
KHD2019 운영사무국입니다.

본 행사는 2019.11.29(금) 12:00부터 등록을 시작하여 13:00부터는 오리엔테이션이 예정되어 있습니다. 
문의하신 별도의 교통편 및 교통비 지원은 없습니다. 

KHD2019는 2019.11.20(수)까지 
https://bit.ly/khd2019-nsml 로 참가신청이 가능하며 참가 여부는 심사 후 개별안내를 드립니다.

자세한 FAQ는 https://github.com/khd2019/khd2019 를 참고부탁드리겠습니다.
추가문의사항은 khd2019-nsml@navercorp.com로 문의주시면 회신드리겠습니다.

감사합니다.

**Comment by HyunjiEllenPak** [comment]
@khd2019 
안녕하세요. 대회준비로 고생이 많으십니다^^! 
이번 해커톤이  대전에서 1박2일로 개최되기에 저희 팀뿐만 아니라 서울에서 참가를 희망하는 팀 중 많은 팀들이 교통편으로 인하여 대회 참여를 고민중일 것 이라 생각되어 문의드립니다.
혹시 서울 근방에서 출발하는 교통편 지원을 고려해주실 수 없을지요?

감사합니다.

**Comment by khd2019** [comment]
> @khd2019
> 안녕하세요. 대회준비로 고생이 많으십니다^^!
> 이번 해커톤이 대전에서 1박2일로 개최되기에 저희 팀뿐만 아니라 서울에서 참가를 희망하는 팀 중 많은 팀들이 교통편으로 인하여 대회 참여를 고민중일 것 이라 생각되어 문의드립니다.
> 혹시 서울 근방에서 출발하는 교통편 지원을 고려해주실 수 없을지요?
> 
> 감사합니다.

안녕하세요.
KHD2019 운영사무국입니다.

먼저 본 행사에 관심을 가져주셔서 진심으로 감사합니다.
참여자에 한하여 병원내 고객주차장을 행사기간중 무상지원 예정이오나 
전국에서 참여하는 행사로 별도의 교통비 지원은 없음을 양해 부탁드리겠습니다.
현재 새병원 증축공사로 인하여 주차공간이 매우 협소하므로 가급적 대중교통 이용을 부탁드리겠습니다.

KHD2019는 2019.11.20(수)까지
https://bit.ly/khd2019-nsml 로 참가신청이 가능하며 참가 여부는 심사 후 개별안내를 드립니다.

자세한 FAQ는 https://github.com/khd2019/khd2019 를 참고부탁드리겠습니다.
추가문의사항은 khd2019-nsml@navercorp.com로 문의주시면 회신드리겠습니다.

감사합니다.
