### ISSUE TITLE
NSML 계정 추가 요청드립니다.

### ISSUE THREAD

**Issue by hidoyebi** [khd2019/khd2019#20]
안녕하세요. 

B조 14팀(ABMI) 김도엽입니다. 대회 참가 신청 후 참가 인원이 변경되면서 새로 참가하게된 팀원이 NSML 계정을 부여받지 못했습니다. 계정 할당을 부탁드려도 될까요? 

팀: B조 14팀(ABMI), ID: hidoyebi

**Comment by okgosu** [comment]
확인 후 다시 업데이트 드리겠습니다.
