### ISSUE TITLE
Dataset spec 궁금합니다.

### ISSUE THREAD

**Issue by karlkwon** [khd2019/khd2019#3]
안녕하세요.
이번에 "유방촬영이미지 학습 알고리즘 성능 평가"에 지원을 했습니다.
그런데 제공되는 dataset의 format이 궁금해서 그러는데 알려 주실수 있나요?
그리고 가능하시면 sample data를 몇장이라고 같이 공유해 주시면 더 좋을 것 같습니다.

**Comment by khd2019** [comment]
> 안녕하세요.
> 이번에 "유방촬영이미지 학습 알고리즘 성능 평가"에 지원을 했습니다.
> 그런데 제공되는 dataset의 format이 궁금해서 그러는데 알려 주실수 있나요?
> 그리고 가능하시면 sample data를 몇장이라고 같이 공유해 주시면 더 좋을 것 같습니다.

안녕하세요.
KHD2019 운영사무국입니다.

data format의 경우 안저영상은 .jpg, 유방영상은 .npz 입니다. KHD2019에서 사용하는 의료영상의 경우 sample data 공개가 어려워, 구글에서 '광각 안저영상' 및 'mammography'로 검색해서 찾아보셔야 합니다. 간단한 데이터셋 설명자료를 업로드 예정이니 참고해주시면 될 것 같습니다. 

자세한 FAQ는 https://github.com/khd2019/khd2019 를 참고부탁드리겠습니다.
추가문의사항은 khd2019-nsml@navercorp.com로 문의주시면 회신드리겠습니다.

감사합니다.

**Comment by karlkwon** [comment]
답변 감사합니다.

제가 잘 이해하고 있는지는 모르겠지만 추가 질문 드립니다.

npz는 압축된 file이고 안에 다시 실 data 들어가 있는것 아닌가요?
(A dictionary-like object with lazy-loading of files in the zipped archive provided on construction.)
그렇다면 실제 이미지 format은 다른게 들어 있는 것이 아닌가요?

제가 다운 받은 공개 dataset들은 .dcm format 이 많던데요.
(https://wiki.cancerimagingarchive.net/display/Public/CBIS-DDSM)

그리고 이미지 공유가 힘드시다면 이미지의 크기와 컬러여부 등은 알수 있을까요?

**Comment by karlkwon** [comment]
code 내용 확인하니 820 x 666 x 1 인것 같네요.
