### ISSUE TITLE
GPU resources 할당량 제한 문의

### ISSUE THREAD

**Issue by rmfkxhxh** [khd2019/khd2019#31]
현재 기준 gpu resources 사용량 77%대로 gpu 20개 가량, cpu 200개 가량이 unoccupied인 상태인데 혹시 팀당 할당량 제한 좀 더 늘려 주실 수 없을까 해서 문의 드립니다.

**Comment by okgosu** [comment]
https://github.com/khd2019/khd2019/issues/13 에 따라 최대 2 GPU 드리고 있는 점 참고 바랍니다.
