### ISSUE TITLE
이미지 프로세싱 하다가 세션이 강제 종료 됩니다.

### ISSUE THREAD

**Issue by sunnys-lab** [khd2019/khd2019#32]
3209 / 3823  image(s)
3210 / 3823  image(s)
3211 / 3823  image(s)
/bin/bash: line 1:    51 Killed                  python -u main_org.py
User session exited

거의 다 하다가 종료되어서 시간만... 제발 처리좀 부탁드립니다. ㅠㅠ

**Comment by rmfkxhxh** [comment]
메모리 부족 error라고 말씀해 주셨었습니다.

**Comment by okgosu** [comment]
https://github.com/khd2019/khd2019/issues/35 참고 바랍니다.
