### ISSUE TITLE
안저영상 베이스 코드 프레임워크 문의

### ISSUE THREAD

**Issue by mulkong** [khd2019/khd2019#6]
안저영상은 베이크 코드가 pytorch 버전은 없을까요....?

**Comment by khd2019** [comment]
> 안저영상은 베이크 코드가 pytorch 버전은 없을까요....?

안녕하세요.
KHD2019 운영사무국입니다.

현재 Fundus 폴더(안저영상)에 업로드 되어있는 코드는 keras로 작성된 샘플코드로 pytorch 버전은 없습니다. 참가자가 pytorch로 이용을 원하실 경우, 코드를 수정해서 사용할 수 있습니다.

자세한 FAQ는 https://github.com/khd2019/khd2019 를 참고부탁드리겠습니다.
추가문의사항은 khd2019-nsml@navercorp.com로 문의주시면 회신드리겠습니다.

감사합니다.
