### ISSUE TITLE
[공지] NSML 계정 접속은 11월 27일 14:00 이후 부터 가능합니다. (에러시 트러블 슈팅 참고)

### ISSUE THREAD

**Issue by okgosu** [khd2019/khd2019#7]
## [NSML 계정 접속](https://ai.nsml.navercorp.com/login)은 11월 27일 14:00 이후 부터 가능합니다.

github 계정으로 NSML 로그인(https://ai.nsml.navercorp.com/login) 이 잘 안될 경우 아래의 사항들을 참고하시길 바랍니다. 

0단계) 본인의 github 아이디 확인 
- 목적: github 아이디와 메일계정을 혼돈하지 않고 파악
- 방법:  github.com에 login하신 후, 자신의 profile 페이지에서 붉은 박스가 본인의 github ID입니다. 대/소문자의 구분이 있으니 제출시 주의하시기 바랍니다. 기 제출한 본인의 github ID에 오류가 있을 경우, 메일로 정정을 요청하시기 바랍니다.
![image](https://user-images.githubusercontent.com/6773678/69685497-edc46f00-10ff-11ea-9c50-c26992210cf9.png)![image](https://user-images.githubusercontent.com/6773678/69685502-f157f600-10ff-11ea-84e0-b44494121746.png)

1단계) KHD2019 참가 접수시 제출한 github 아이디 확인
- 목적: KHD2019 참가 접수시제출한 github 아이디가 NSML 로그인하려는 아이디와 일치하는지 확인
- 해결방법: KHD2019사무국에 보낸 메일의 github 아이디가 맞는지 확인 

2단계)  github id와 pw 확인
- 목적: 본인이 알고 있는 github id와 pw가 맞는지 확인 
- 해결방법: github에서 로그아웃 한 다음, 모든 브라우저를 닫고 새로운 창에서  github에 정상적으로 로그인이 되는지 확인 

3단계) 로그인 실패 횟수 확인
- 목적: NSML은 로그인 실패가 5회가 되면 계정이 일시 잠깁니다.
- 해결방법 : 아이디 비번을 정확히 확인 한 후 15분 정도 후에 다시 시도합니다.  

4단계) NSML 터미널 버전 확인
- 목적: NSML 터미널은 KHD2019용 터미널을 다운받아 사용해야합니다. 다른 NSML 터미널을 사용하시면 안됩니다.
- 해결방법: https://ai.nsml.navercorp.com/download 에서 다운받고, 해당 NSML 경로를 path에 등록

**Comment by okgosu** [comment]
아직 NSML시스템에 github 계정 세팅이 되지 않은 상태입니다. 완료되면 다시 공지 드리겠습니다.

**Comment by Yupjun** [comment]
https://ai.nsml.navercorp.com/download  여기 들어가 보면 khd용 nsml은 따로 버전 명시가 안되어 있는데요 그냥 다운받으면 되나요?

**Comment by okgosu** [comment]
@Yupjun 네, 버전은 따로 없습니다. 접속테스트는 11월 26일(화) 오후 5시 이후 팀대표 github 계정으로 하시기를 바랍니다.

**Comment by parkjoohwan** [comment]
접속테스트를 위해 로그인을 시도해봤는데 
```
time="2019/11/26 19:42:40.925" level=fatal msg="login failed: You are not a registered user" 
```
라고 나오는데 아직 세팅이 안된걸까요?

**Comment by okgosu** [comment]
@parkjoohwan 님, 불편을 드려 죄송합니다. 11/27일 14:00로 계정 작업 완료예정입니다

**Comment by heozzi** [comment]
NSML로 깃허브 로그인 하려고 하면 
time="2019/11/28 13:18:22.919" level=fatal msg="login failed: Login server error" 
같은 오류가 발생하는데 해결 할 방법이 있나요?

**Comment by okgosu** [comment]
@heozzi 이용에 불편을 드려 죄송합니다. https://ai.nsml.navercorp.com 에는 로그인은 되는거죠? 
빠르게  이슈 내용 확인 후 다시 업데이트 드릴게요.

**Comment by heozzi** [comment]
넵 사이트는 문제없이 로그인이 됩니다.
-----Original Message-----

**Comment by okgosu** [comment]
@heozzi 터미널에서 로그인을 여러차례 실패해서 나오는 이슈 같네요. 30분 정도 후에 아이디 암호 정확히 확인하신 후 다시 해보시길 바랍니다.

**Comment by ssunhye** [comment]
https://ai.nsml.navercorp.com 에는 로그인이 됩니다.
그러나 터미널에서 nsml login 을 하면
time="2019/11/28 14:26:37.413" level=fatal msg="login failed: Login server error"
라는 에러가 뜹니다.
한번 확인 부탁드립니다!

**Comment by BupyeongHealer** [comment]
안녕하세요! 저도 nsml login 이슈로 문의드립니다!
github id가 등록되어 있지 않은 것 같아 확인 부탁드립니다!
time="2019/11/28 14:42:42.824" level=fatal msg="login failed: You are not a registered user"

또, https://ai.nsml.navercorp.com 에서 확인을 해보니,
You are not a registered user. Please contact the administrator. ( dl_nsml_alpha@navercorp.com )
상태가 뜹니다. 감사합니다!

**Comment by heozzi** [comment]
30분이 지난 후에 로그인을 하여도 로그인이 되지 않고 있습니다.

**Comment by Taeu** [comment]
안녕하세요, 저도 nsml login이 되지 않아 문의드립니다!

https://ai.nsml.navercorp.com 에서 확인해보니,
You are not a registered user. Please contact the administrator. ( dl_nsml_alpha@navercorp.com )
라고 뜹니다.

아직 등록이 되지 않은 것일까요?

**Comment by okgosu** [comment]
@heozzi @Taeu @BupyeongHealer @ssunhye 님 로그인 되는지 확인 부탁드립니다. 안되면 행사장에서 말씀주세요.

**Comment by heozzi** [comment]
현재는 문제 없이 로그인 됩니다.
감사합니다.

**Comment by ssunhye** [comment]
로그인 됩니다! 감사합니다

**Comment by okgosu** [comment]
yupjun, bryanshim  로그인 설정 확인 후 말씀드릴게요.

@Yupjun  @bryanshim

**Comment by siksimi** [comment]
로그인은되는데 다음 에러가 지속적으로 발생하고 있습니다.. 감사합니다.

팀명 넥스트
ID siksimi 입니다.

D:\nsml\test\mnist-example>nsml run -d mnist2
time="2019/11/29 13:31:53.245" level=info msg=".nsmlignore check - start"
time="2019/11/29 13:31:53.271" level=info msg=".nsmlignore check - done"
time="2019/11/29 13:31:53.339" level=info msg="file integrity check - start"
time="2019/11/29 13:31:53.344" level=info msg="file integrity check - done"
time="2019/11/29 13:31:53.347" level=info msg="README.md 5.1 KiB - start"
time="2019/11/29 13:31:53.358" level=info msg="README.md 5.1 KiB - done (1/7 14.29%) (5.1 KiB/40 KiB 12.85%)"
time="2019/11/29 13:31:53.363" level=info msg="ladder.py 10 KiB - start"
time="2019/11/29 13:31:53.373" level=info msg="ladder.py 10 KiB - done (2/7 28.57%) (15 KiB/40 KiB 38.03%)"
time="2019/11/29 13:31:53.378" level=info msg="main.py 8.4 KiB - start"
time="2019/11/29 13:31:53.389" level=info msg="main.py 8.4 KiB - done (3/7 42.86%) (24 KiB/40 KiB 58.93%)"
time="2019/11/29 13:31:53.394" level=info msg="none_test.py 4.5 KiB - start"
time="2019/11/29 13:31:53.405" level=info msg="none_test.py 4.5 KiB - done (4/7 57.14%) (28 KiB/40 KiB 70.23%)"
time="2019/11/29 13:31:53.410" level=info msg="ops.py 3.7 KiB - start"
time="2019/11/29 13:31:53.419" level=info msg="ops.py 3.7 KiB - done (5/7 71.43%) (32 KiB/40 KiB 79.49%)"
time="2019/11/29 13:31:53.425" level=info msg="rladder.py 8.0 KiB - start"
time="2019/11/29 13:31:53.435" level=info msg="rladder.py 8.0 KiB - done (6/7 85.71%) (40 KiB/40 KiB 99.39%)"
time="2019/11/29 13:31:53.442" level=info msg="setup.py 252 B - start"
time="2019/11/29 13:31:53.449" level=info msg="setup.py 252 B - done (7/7 100.00%) (40 KiB/40 KiB 100.00%)"
**.Error: An error occurred while initializing user information. Please contact dev team
time="2019/11/29 13:31:54.201" level=fatal msg="Internal server error"**

**Comment by bluebrush** [comment]
@siksimi 님 재시도 부탁드립니다.

**Comment by siksimi** [comment]
@bluebrush 해결되었습니다. 감사합니다!

**Comment by parkjoohwan** [comment]
```
$nsml run -d mnist2
time="2019/11/29 14:27:23.465" level=info msg=".nsmlignore check - start"
time="2019/11/29 14:27:23.530" level=info msg=".nsmlignore check - done"
time="2019/11/29 14:27:23.608" level=info msg="file integrity check - start"
time="2019/11/29 14:27:23.609" level=info msg="file integrity check - done"
time="2019/11/29 14:27:23.609" level=info msg="README.md 5.1 KiB - start"
time="2019/11/29 14:27:23.609" level=info msg="README.md 5.1 KiB - done (1/7 14.29%) (5.1 KiB/40 KiB 12.85%)"
time="2019/11/29 14:27:23.610" level=info msg="ladder.py 10 KiB - start"
time="2019/11/29 14:27:23.610" level=info msg="ladder.py 10 KiB - done (2/7 28.57%) (15 KiB/40 KiB 38.03%)"
time="2019/11/29 14:27:23.610" level=info msg="main.py 8.4 KiB - start"
time="2019/11/29 14:27:23.610" level=info msg="main.py 8.4 KiB - done (3/7 42.86%) (24 KiB/40 KiB 58.93%)"
time="2019/11/29 14:27:23.610" level=info msg="none_test.py 4.5 KiB - start"
time="2019/11/29 14:27:23.610" level=info msg="none_test.py 4.5 KiB - done (4/7 57.14%) (28 KiB/40 KiB 70.23%)"
time="2019/11/29 14:27:23.610" level=info msg="ops.py 3.7 KiB - start"
time="2019/11/29 14:27:23.610" level=info msg="ops.py 3.7 KiB - done (5/7 71.43%) (32 KiB/40 KiB 79.49%)"
time="2019/11/29 14:27:23.611" level=info msg="rladder.py 8.0 KiB - start"
time="2019/11/29 14:27:23.611" level=info msg="rladder.py 8.0 KiB - done (6/7 85.71%) (40 KiB/40 KiB 99.39%)"
time="2019/11/29 14:27:23.611" level=info msg="setup.py 252 B - start"
time="2019/11/29 14:27:23.611" level=info msg="setup.py 252 B - done (7/7 100.00%) (40 KiB/40 KiB 100.00%)"

.Error: An error occurred while initializing user information. Please contact dev team
time="2019/11/29 14:27:24.425" level=fatal msg="Internal server error"
```
저도 에러문구 출력되는데 확인해 주실 수 있을까요?

팀 : 기본에 충실함
ID : parkjoohwan 

입니다 @okgosu

**Comment by hidoyebi** [comment]
@okgosu 안녕하세요. B조 14팀(ABMI) 김도엽입니다. 대회 참가 신청 후 참가 인원이 변경되면서 새로 참가하게된 팀원이 NSML 계정을 부여받지 못한 것 같습니다. 계정 할당을 부탁드려도 될까요? 팀: B조 14팀(ABMI) 김도엽, ID: hidoyebi

**Comment by okgosu** [comment]
본 이슈는 완료되어 close 합니다.
